language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

jobs:
  allow_failures:
    - php: 8.0

before_script:
  - composer self-update
  - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then NTESTER_FLAGS="phpdbg --coverage ./coverage.xml --coverage-src ./src"; else TESTER_FLAGS=""; fi


after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then
    wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    && php coveralls.phar --verbose --config tests/.coveralls.yml
    || true;
    fi

script:
  - ./tests/run-tests $NTESTER_FLAGS
